name: Build Project
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/main.yml
  pull_request:
    branches:
    - main
    paths:
      - src/**
      - .github/workflows/main.yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          lfs: true
    - uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneWindows64
    - uses: game-ci/unity-builder@v4
      id: myBuildStep
      - run: echo 'Project Version: ${{ steps.myBuildStep.outputs.buildVersion }}'
    - uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build